language: generic
dist: bionic

before_install:
  - curl -sSf --retry 5 -o python-3.8.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/18.04/x86_64/python-3.8.tar.bz2
  - sudo tar xjf python-3.8.tar.bz2 --directory /
  - curl -sSf --retry 5 -o python-3.7.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/18.04/x86_64/python-3.7.tar.bz2
  - sudo tar xjf python-3.7.tar.bz2 --directory /
  - curl -sSf --retry 5 -o pypy2.7-7.2.0.tar.bz2 https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/18.04/x86_64/pypy2.7-7.2.0.tar.bz2
  - sudo tar xjf pypy2.7-7.2.0.tar.bz2 --directory /
  - python2.7 --version
  - python3.7 --version
  - python3.8 --version
  - pypy --version
  - sudo apt-get update
  - sudo apt install -y python3-pip

install:
  - pip3 install setuptools
  - pip3 install --user nox

script:
  - nox -e test
  - nox -e lint
