language: python
python:
  - "3.7"
dist: bionic

before_install:
  - sudo pyenv install python2.7
  - sudo pyenv install python3.8
  - sudo pyenv install pypy
  - python2.7 --version
  - python3.7 --version
  - python3.8 --version
  - pypy --version
  - sudo apt-get update
  - sudo apt install -y python3-pip

install:
  - pip3 install setuptools
  - pip3 install --user nox

script:
  - nox -e test
  - nox -e lint
