language: python
python:
  - "3.7"
dist: bionic

before_install:
  - pyenv install -s 2.7
  - pyenv install -s 3.8
  - pyenv install -s pypy
  - python2.7 --version
  - python3.7 --version
  - python3.8 --version
  - pypy --version

install:
  - pip install setuptools
  - pip install --user nox

script:
  - nox -e test
  - nox -e lint
